// Code generated by counterfeiter. DO NOT EDIT.
package handlerfakes

import (
	"sync"

	"github.com/georgisomnoev/feature-flag-api/internal/featureflags/handler"
	jwt "github.com/golang-jwt/jwt/v5"
)

type FakeJWTHelper struct {
	ValidateTokenStub        func(string) (jwt.MapClaims, error)
	validateTokenMutex       sync.RWMutex
	validateTokenArgsForCall []struct {
		arg1 string
	}
	validateTokenReturns struct {
		result1 jwt.MapClaims
		result2 error
	}
	validateTokenReturnsOnCall map[int]struct {
		result1 jwt.MapClaims
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJWTHelper) ValidateToken(arg1 string) (jwt.MapClaims, error) {
	fake.validateTokenMutex.Lock()
	ret, specificReturn := fake.validateTokenReturnsOnCall[len(fake.validateTokenArgsForCall)]
	fake.validateTokenArgsForCall = append(fake.validateTokenArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateTokenStub
	fakeReturns := fake.validateTokenReturns
	fake.recordInvocation("ValidateToken", []interface{}{arg1})
	fake.validateTokenMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeJWTHelper) ValidateTokenCallCount() int {
	fake.validateTokenMutex.RLock()
	defer fake.validateTokenMutex.RUnlock()
	return len(fake.validateTokenArgsForCall)
}

func (fake *FakeJWTHelper) ValidateTokenCalls(stub func(string) (jwt.MapClaims, error)) {
	fake.validateTokenMutex.Lock()
	defer fake.validateTokenMutex.Unlock()
	fake.ValidateTokenStub = stub
}

func (fake *FakeJWTHelper) ValidateTokenArgsForCall(i int) string {
	fake.validateTokenMutex.RLock()
	defer fake.validateTokenMutex.RUnlock()
	argsForCall := fake.validateTokenArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeJWTHelper) ValidateTokenReturns(result1 jwt.MapClaims, result2 error) {
	fake.validateTokenMutex.Lock()
	defer fake.validateTokenMutex.Unlock()
	fake.ValidateTokenStub = nil
	fake.validateTokenReturns = struct {
		result1 jwt.MapClaims
		result2 error
	}{result1, result2}
}

func (fake *FakeJWTHelper) ValidateTokenReturnsOnCall(i int, result1 jwt.MapClaims, result2 error) {
	fake.validateTokenMutex.Lock()
	defer fake.validateTokenMutex.Unlock()
	fake.ValidateTokenStub = nil
	if fake.validateTokenReturnsOnCall == nil {
		fake.validateTokenReturnsOnCall = make(map[int]struct {
			result1 jwt.MapClaims
			result2 error
		})
	}
	fake.validateTokenReturnsOnCall[i] = struct {
		result1 jwt.MapClaims
		result2 error
	}{result1, result2}
}

func (fake *FakeJWTHelper) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeJWTHelper) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handler.JWTHelper = new(FakeJWTHelper)
