// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../observability/templates/otel_trace.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package trace

import (
	"context"

	_sourceHandler "github.com/georgisomnoev/feature-flag-api/internal/featureflags/handler"
	"github.com/google/uuid"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	_codes "go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

// AuthStoreWithTracing implements AuthStore interface instrumented with open telemetry spans
type AuthStoreWithTracing struct {
	_sourceHandler.AuthStore
	tracer trace.Tracer
}

// NewAuthStoreWithTracing returns AuthStoreWithTracing
func NewAuthStoreWithTracing(base _sourceHandler.AuthStore) AuthStoreWithTracing {
	d := AuthStoreWithTracing{
		AuthStore: base,
		tracer:    otel.GetTracerProvider().Tracer(""),
	}

	return d
}

// UserExists implements AuthStore
func (_d AuthStoreWithTracing) UserExists(ctx context.Context, id uuid.UUID) (b1 bool, err error) {
	ctx, _span := _d.tracer.Start(ctx, "AuthStore.UserExists")
	defer func() {
		if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}
		_span.End()
	}()
	return _d.AuthStore.UserExists(ctx, id)
}
