// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../observability/templates/otel_trace.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package trace

import (
	_sourceHandler "github.com/georgisomnoev/feature-flag-api/internal/featureflags/handler"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/trace"
)

// JWTHelperWithTracing implements JWTHelper interface instrumented with open telemetry spans
type JWTHelperWithTracing struct {
	_sourceHandler.JWTHelper
	tracer trace.Tracer
}

// NewJWTHelperWithTracing returns JWTHelperWithTracing
func NewJWTHelperWithTracing(base _sourceHandler.JWTHelper) JWTHelperWithTracing {
	d := JWTHelperWithTracing{
		JWTHelper: base,
		tracer:    otel.GetTracerProvider().Tracer(""),
	}

	return d
}
