run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet             
    - errcheck          
    - staticcheck       
    - gosimple          
    - unused            
    - ineffassign       
    - typecheck            
    - goconst           
    - gofmt             
    - goimports         
    - misspell          
    - nakedret          
    - unconvert         