// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../observability/templates/otel_trace.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package trace

import (
	"context"

	"github.com/georgisomnoev/feature-flag-api/internal/featureflags/model"
	_sourceService "github.com/georgisomnoev/feature-flag-api/internal/featureflags/service"
	"github.com/google/uuid"

	_codes "go.opentelemetry.io/otel/codes"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

// StoreWithTracing implements Store interface instrumented with open telemetry spans
type StoreWithTracing struct {
	_sourceService.Store
	tracer trace.Tracer
}

// NewStoreWithTracing returns StoreWithTracing
func NewStoreWithTracing(base _sourceService.Store) StoreWithTracing {
	d := StoreWithTracing{
		Store:  base,
		tracer: otel.GetTracerProvider().Tracer(""),
	}

	return d
}

// CreateFlag implements Store
func (_d StoreWithTracing) CreateFlag(ctx context.Context, flag model.FeatureFlag) (err error) {
	ctx, _span := _d.tracer.Start(ctx, "Store.CreateFlag")
	defer func() {
		if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}
		_span.End()
	}()
	return _d.Store.CreateFlag(ctx, flag)
}

// DeleteFlag implements Store
func (_d StoreWithTracing) DeleteFlag(ctx context.Context, id uuid.UUID) (err error) {
	ctx, _span := _d.tracer.Start(ctx, "Store.DeleteFlag")
	defer func() {
		if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}
		_span.End()
	}()
	return _d.Store.DeleteFlag(ctx, id)
}

// GetFlagByID implements Store
func (_d StoreWithTracing) GetFlagByID(ctx context.Context, id uuid.UUID) (f1 model.FeatureFlag, err error) {
	ctx, _span := _d.tracer.Start(ctx, "Store.GetFlagByID")
	defer func() {
		if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}
		_span.End()
	}()
	return _d.Store.GetFlagByID(ctx, id)
}

// ListFlags implements Store
func (_d StoreWithTracing) ListFlags(ctx context.Context) (fa1 []model.FeatureFlag, err error) {
	ctx, _span := _d.tracer.Start(ctx, "Store.ListFlags")
	defer func() {
		if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}
		_span.End()
	}()
	return _d.Store.ListFlags(ctx)
}

// UpdateFlag implements Store
func (_d StoreWithTracing) UpdateFlag(ctx context.Context, flag model.FeatureFlag) (err error) {
	ctx, _span := _d.tracer.Start(ctx, "Store.UpdateFlag")
	defer func() {
		if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}
		_span.End()
	}()
	return _d.Store.UpdateFlag(ctx, flag)
}
