// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../observability/templates/otel_metric.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package metric

import (
	"context"
	"time"

	"github.com/georgisomnoev/feature-flag-api/internal/auth/model"
	_sourceService "github.com/georgisomnoev/feature-flag-api/internal/auth/service"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

type StoreMetrics struct {
	RequestCounter  metric.Int64Counter
	RequestDuration metric.Float64Histogram
}

type StoreWithMetrics struct {
	base    _sourceService.Store
	metrics *StoreMetrics
}

func NewStoreWithMetrics(base _sourceService.Store) *StoreWithMetrics {
	meter := otel.GetMeterProvider().Meter("")

	requestCounter, _ := meter.Int64Counter("Store_requests_total", metric.WithDescription("Total number of Store method calls"))
	durationHistogram, _ := meter.Float64Histogram("Store_request_duration_ms", metric.WithDescription("Duration of Store method calls in milliseconds"))

	return &StoreWithMetrics{
		base: base,
		metrics: &StoreMetrics{
			RequestCounter:  requestCounter,
			RequestDuration: durationHistogram,
		},
	}
}

func (_d *StoreWithMetrics) GetByUsername(ctx context.Context, s1 string) (up1 *model.User, err error) {
	startTime := time.Now()

	var metricCtx context.Context

	metricCtx = ctx

	if metricCtx == nil {
		metricCtx = context.Background()
	}

	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		_d.metrics.RequestCounter.Add(metricCtx, 1,
			metric.WithAttributes(
				attribute.String("method", "GetByUsername"),
				attribute.String("status", result),
			),
		)
		duration := float64(time.Since(startTime).Milliseconds())
		_d.metrics.RequestDuration.Record(metricCtx, duration, metric.WithAttributes(attribute.String("method", "GetByUsername")))
	}()
	return _d.base.GetByUsername(ctx, s1)
}
