// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"sync"

	"github.com/georgisomnoev/feature-flag-api/internal/auth/service"
	jwt "github.com/golang-jwt/jwt/v5"
)

type FakeJWTHelper struct {
	GenerateTokenStub        func(jwt.Claims) (string, error)
	generateTokenMutex       sync.RWMutex
	generateTokenArgsForCall []struct {
		arg1 jwt.Claims
	}
	generateTokenReturns struct {
		result1 string
		result2 error
	}
	generateTokenReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJWTHelper) GenerateToken(arg1 jwt.Claims) (string, error) {
	fake.generateTokenMutex.Lock()
	ret, specificReturn := fake.generateTokenReturnsOnCall[len(fake.generateTokenArgsForCall)]
	fake.generateTokenArgsForCall = append(fake.generateTokenArgsForCall, struct {
		arg1 jwt.Claims
	}{arg1})
	stub := fake.GenerateTokenStub
	fakeReturns := fake.generateTokenReturns
	fake.recordInvocation("GenerateToken", []interface{}{arg1})
	fake.generateTokenMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeJWTHelper) GenerateTokenCallCount() int {
	fake.generateTokenMutex.RLock()
	defer fake.generateTokenMutex.RUnlock()
	return len(fake.generateTokenArgsForCall)
}

func (fake *FakeJWTHelper) GenerateTokenCalls(stub func(jwt.Claims) (string, error)) {
	fake.generateTokenMutex.Lock()
	defer fake.generateTokenMutex.Unlock()
	fake.GenerateTokenStub = stub
}

func (fake *FakeJWTHelper) GenerateTokenArgsForCall(i int) jwt.Claims {
	fake.generateTokenMutex.RLock()
	defer fake.generateTokenMutex.RUnlock()
	argsForCall := fake.generateTokenArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeJWTHelper) GenerateTokenReturns(result1 string, result2 error) {
	fake.generateTokenMutex.Lock()
	defer fake.generateTokenMutex.Unlock()
	fake.GenerateTokenStub = nil
	fake.generateTokenReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeJWTHelper) GenerateTokenReturnsOnCall(i int, result1 string, result2 error) {
	fake.generateTokenMutex.Lock()
	defer fake.generateTokenMutex.Unlock()
	fake.GenerateTokenStub = nil
	if fake.generateTokenReturnsOnCall == nil {
		fake.generateTokenReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.generateTokenReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeJWTHelper) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeJWTHelper) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.JWTHelper = new(FakeJWTHelper)
