// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../observability/templates/otel_metric.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package metric

import (
	"context"
	"time"

	"github.com/georgisomnoev/feature-flag-api/internal/featureflags/model"
	_sourceService "github.com/georgisomnoev/feature-flag-api/internal/featureflags/service"
	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

type StoreMetrics struct {
	RequestCounter  metric.Int64Counter
	RequestDuration metric.Float64Histogram
}

type StoreWithMetrics struct {
	base    _sourceService.Store
	metrics *StoreMetrics
}

func NewStoreWithMetrics(base _sourceService.Store) *StoreWithMetrics {
	meter := otel.GetMeterProvider().Meter("")

	requestCounter, _ := meter.Int64Counter("Store_requests_total", metric.WithDescription("Total number of Store method calls"))
	durationHistogram, _ := meter.Float64Histogram("Store_request_duration_ms", metric.WithDescription("Duration of Store method calls in milliseconds"))

	return &StoreWithMetrics{
		base: base,
		metrics: &StoreMetrics{
			RequestCounter:  requestCounter,
			RequestDuration: durationHistogram,
		},
	}
}

func (_d *StoreWithMetrics) CreateFlag(ctx context.Context, flag model.FeatureFlag) (err error) {
	startTime := time.Now()

	var metricCtx context.Context

	metricCtx = ctx

	if metricCtx == nil {
		metricCtx = context.Background()
	}

	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		_d.metrics.RequestCounter.Add(metricCtx, 1,
			metric.WithAttributes(
				attribute.String("method", "CreateFlag"),
				attribute.String("status", result),
			),
		)
		duration := float64(time.Since(startTime).Milliseconds())
		_d.metrics.RequestDuration.Record(metricCtx, duration, metric.WithAttributes(attribute.String("method", "CreateFlag")))
	}()
	return _d.base.CreateFlag(ctx, flag)
}

func (_d *StoreWithMetrics) DeleteFlag(ctx context.Context, id uuid.UUID) (err error) {
	startTime := time.Now()

	var metricCtx context.Context

	metricCtx = ctx

	if metricCtx == nil {
		metricCtx = context.Background()
	}

	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		_d.metrics.RequestCounter.Add(metricCtx, 1,
			metric.WithAttributes(
				attribute.String("method", "DeleteFlag"),
				attribute.String("status", result),
			),
		)
		duration := float64(time.Since(startTime).Milliseconds())
		_d.metrics.RequestDuration.Record(metricCtx, duration, metric.WithAttributes(attribute.String("method", "DeleteFlag")))
	}()
	return _d.base.DeleteFlag(ctx, id)
}

func (_d *StoreWithMetrics) GetFlagByID(ctx context.Context, id uuid.UUID) (f1 model.FeatureFlag, err error) {
	startTime := time.Now()

	var metricCtx context.Context

	metricCtx = ctx

	if metricCtx == nil {
		metricCtx = context.Background()
	}

	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		_d.metrics.RequestCounter.Add(metricCtx, 1,
			metric.WithAttributes(
				attribute.String("method", "GetFlagByID"),
				attribute.String("status", result),
			),
		)
		duration := float64(time.Since(startTime).Milliseconds())
		_d.metrics.RequestDuration.Record(metricCtx, duration, metric.WithAttributes(attribute.String("method", "GetFlagByID")))
	}()
	return _d.base.GetFlagByID(ctx, id)
}

func (_d *StoreWithMetrics) ListFlags(ctx context.Context) (fa1 []model.FeatureFlag, err error) {
	startTime := time.Now()

	var metricCtx context.Context

	metricCtx = ctx

	if metricCtx == nil {
		metricCtx = context.Background()
	}

	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		_d.metrics.RequestCounter.Add(metricCtx, 1,
			metric.WithAttributes(
				attribute.String("method", "ListFlags"),
				attribute.String("status", result),
			),
		)
		duration := float64(time.Since(startTime).Milliseconds())
		_d.metrics.RequestDuration.Record(metricCtx, duration, metric.WithAttributes(attribute.String("method", "ListFlags")))
	}()
	return _d.base.ListFlags(ctx)
}

func (_d *StoreWithMetrics) UpdateFlag(ctx context.Context, flag model.FeatureFlag) (err error) {
	startTime := time.Now()

	var metricCtx context.Context

	metricCtx = ctx

	if metricCtx == nil {
		metricCtx = context.Background()
	}

	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		_d.metrics.RequestCounter.Add(metricCtx, 1,
			metric.WithAttributes(
				attribute.String("method", "UpdateFlag"),
				attribute.String("status", result),
			),
		)
		duration := float64(time.Since(startTime).Milliseconds())
		_d.metrics.RequestDuration.Record(metricCtx, duration, metric.WithAttributes(attribute.String("method", "UpdateFlag")))
	}()
	return _d.base.UpdateFlag(ctx, flag)
}
