name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Basic CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=2m
      
      - name: Run security check
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: Generate certificates and keys
        run: make jwt-keys
      
      - name: Get dependencies
        run: make vendor

      - name: Run the app
        run: |
          cp .env.example .env 
          make run-app

      - name: Run all the tests
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
          make test
      
      - name: Build Docker image
        run: |
          docker build -t feature-flag-api:ci .

      - name: Clean up resources
        if: always()
        run: |
          rm -f .env
          docker system prune -af --volumes

